sources:
  - name: refi-medellin-ubi
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/102458/refi-medellin-ubi/version/latest

documents:
  - ./src/queries/beneficiaries.graphql
  - ./src/queries/funds.graphql
  - ./src/queries/dailyClaims.graphql
